# Utiliser l'image officielle MySQL 

FROM mysql:8.0 

# Définir les variables d'environnement pour MySQL 

ENV MYSQL_ROOT_PASSWORD root 
ENV MYSQL_DATABASE ma_BDD_SQL 
ENV MYSQL_USER amad03 
ENV MYSQL_PASSWORD @_2008 


